version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: reward-postgres
    environment:
      POSTGRES_DB: reward_management
      POSTGRES_USER: reward_user
      POSTGRES_PASSWORD: reward_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    networks:
      - reward-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reward_user -d reward_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: reward-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reward-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  reward-network:
    driver: bridge
